# Generated by Django 4.2.17 on 2024-12-17 16:55

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="category/images/",
                validators=[service.models.validate_image_type],
            ),
        ),
    ]
