# Generated by Django 4.2.17 on 2024-12-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("discount", models.CharField(max_length=50)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="offer_images/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
